<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ek9</string>
	</array>
	<key>name</key>
	<string>ek9</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.ek9</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>comment.block.ek9</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;\?-</string>
			<key>end</key>
			<string>-\?&gt;</string>
			<key>name</key>
			<string>comment.block.ek9</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!-</string>
			<key>end</key>
			<string>-!&gt;</string>
			<key>name</key>
			<string>comment.block.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|by|in|is|allow|extends|do|switch|given|case|when|default|register|aspect|while|for|references|module|operator|defines|as|of|then)\b</string>
			<key>name</key>
			<string>markup.bold.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(try|throw|catch|handle|finally|constrain|range|assert|GET|HEAD|POST|PUT|PATCH|HEADER|PATH|QUERY|BODY)\b</string>
			<key>name</key>
			<string>markup.bold.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mod|rem|sqrt|and|or|xor|abs|not|contain|contains|matches|begins|ends|length|read|write|open|close|override|public|private|protected|return|with|isolated|pure|abstract|dispatcher|only)\b</string>
			<key>name</key>
			<string>keyword.operator.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|cat|filter|group|split|call|async|package|map|sort|flatten|uniq|tee|head|tail|skip|join|collect|reduce)\b</string>
			<key>name</key>
			<string>keyword.other.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(constant|references|application|program|class|component|validator|procedure|text|model|media|trait|function|type|record|service|decoration|style)\b</string>
			<key>name</key>
			<string>storage.type.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Boolean|String|Strings|Integer|Float|Date|Time|DateTime|Font|Colour|Colour|Dimension|RegEx|Duration|Millisecond|Money|Locale|Version|List|Dict|DictEntry|Bits|Map|Optional|Iterator)\b</string>
			<key>name</key>
			<string>storage.type.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|:=|::|&lt;&gt;|!=|&lt;~&gt;|\[|\]|\{|\}|&lt;=&gt;|&lt;=|&gt;=|\*=|/=|\+=|-=|=|!|&gt;&gt;|&lt;&lt;|-&gt;|&lt;-|&lt;|&gt;|\?|\+\+|--|\+|-|~|\*|/|\^|#!|#\?|#&lt;|#&gt;|:|\.\.\.|,|\$|\$\$)</string>
			<key>name</key>
			<string>constant.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>markup.underline.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d*\.\d+\w*|\d+\w*)\b</string>
			<key>name</key>
			<string>string.other.ek9</string>
		</dict>
		<dict>
			<key>match</key>
			<string>""</string>
			<key>name</key>
			<string>string.quoted.double.ek9</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ek9</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.ek9</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>``</string>
			<key>name</key>
			<string>string.quoted.backtick.ek9</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.quoted.backtick.ek9</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.ek9</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>indent-block</key>
		<dict>
			<key>begin</key>
			<string>"^(\\s+)(?=\\S)"</string>
			<key>end</key>
			<string>^(?!\\1\\s+)(?!\s*$)</string>
			<key>name</key>
			<string>indent-block.ek9</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#self</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ek9</string>
	<key>uuid</key>
	<string>798FC8B5-BA48-48E5-B9D4-35A37130F69D</string>
</dict>
</plist>
