package org.company.dept;

import org.ek9tooling.Ek9Function;

/**
 * Models a generic function for handling events.
 */
@Ek9Function("""
    EventHandler of type T
      -> event as T""")
public class EventHandler {

  public EventHandler() {
    //Default constructor - not exposed in any way to EK9
  }

  //Note that the EK9 compiler will call this method.
  public void _call(Object event) {
    //Now when generated by the EK9 compiler, this can call any 'operator' on the event object.
    System.out.println("Event [" + event.toString() +"]");
  }
}
