package org.ek9lang.compiler.bytecode;

import java.util.List;
import org.ek9lang.compiler.support.SymbolCountCheck;

/**
 * Test bytecode generation and execution for synthetic operators with inheritance
 * where super HAS {@literal <=>} but LACKS {@literal ==}.
 *
 * <p>This test validates that when the parent class has one operator but NOT another,
 * the generated bytecode correctly calls super only for the operator that exists.</p>
 *
 * <p>Scenario:</p>
 * <ul>
 *   <li>Animal (parent) has default operator {@literal <=>} but NOT default operator ==</li>
 *   <li>Cat (child) has BOTH default operator {@literal <=>} and default operator ==</li>
 * </ul>
 *
 * <p>Expected bytecode patterns:</p>
 * <ul>
 *   <li>Cat._cmp() SHOULD call super._cmp() (Animal HAS {@literal <=>})</li>
 *   <li>Cat._eq() should NOT call super._eq() (Animal doesn't have ==)</li>
 *   <li>Cat._eq() only compares Cat's own fields</li>
 * </ul>
 */
class SyntheticInheritanceSuperLacksEqOperatorTest extends AbstractExecutableBytecodeTest {

  public SyntheticInheritanceSuperLacksEqOperatorTest() {
    super("/examples/bytecodeGeneration/syntheticInheritanceSuperLacksEqOperator",
        "bytecode.syntheticInheritanceSuperLacksEqOperator",
        "TestSyntheticInheritanceSuperLacksEqOperator",
        List.of(new SymbolCountCheck("bytecode.syntheticInheritanceSuperLacksEqOperator", 3)));
  }
}
