package org.ek9lang.compiler.bytecode;

import java.util.List;
import org.ek9lang.compiler.support.SymbolCountCheck;

/**
 * Test bytecode generation and execution for synthetic operators with inheritance
 * where super HAS the same operator.
 *
 * <p>This test validates that when both parent and child have the same default operator,
 * the generated bytecode correctly calls super's operator before comparing child's fields.</p>
 *
 * <p>Scenario:</p>
 * <ul>
 *   <li>Animal (parent) has default operator {@literal <=>} and default operator ?</li>
 *   <li>Cat (child) extends Animal and also has both operators</li>
 * </ul>
 *
 * <p>Expected bytecode patterns:</p>
 * <ul>
 *   <li>Cat._cmp() should call super._cmp() first (invokespecial on parent)</li>
 *   <li>Cat._cmp() then compares Cat's own fields (breed)</li>
 *   <li>Cat._isSet() checks only Cat's fields (does NOT call super._isSet())</li>
 * </ul>
 */
class SyntheticInheritanceSuperHasOperatorTest extends AbstractExecutableBytecodeTest {

  public SyntheticInheritanceSuperHasOperatorTest() {
    super("/examples/bytecodeGeneration/syntheticInheritanceSuperHasOperator",
        "bytecode.syntheticInheritanceSuperHasOperator",
        "TestSyntheticInheritanceSuperHasOperator",
        List.of(new SymbolCountCheck("bytecode.syntheticInheritanceSuperHasOperator", 3)));
  }
}
