package org.ek9lang.compiler.bytecode;

import java.util.List;
import org.ek9lang.compiler.support.SymbolCountCheck;

/**
 * Test bytecode generation for try-with-resources (single resource).
 * This test has showBytecode=true to output generated bytecode for validation.
 *
 * Validates:
 * - Resource initialization before try block
 * - Automatic close() call in finally block
 * - Exception table includes finally handler
 * - Resource cleanup happens on normal and exception paths
 */
class TryWithSingleResourceTest extends AbstractBytecodeGenerationTest {

  public TryWithSingleResourceTest() {
    // Module: bytecode.test
    // Expected symbols: TestResource class (1) + TryWithSingleResource program (1) = 2
    // showBytecode = true to see generated bytecode in stdout
    super("/examples/bytecodeGeneration/tryWithSingleResource",
        List.of(new SymbolCountCheck("bytecode.test", 2)),
        false, false, true);  // verbose=false, muteErrors=false, showBytecode=true
  }

  @Override
  protected boolean addDebugInstrumentation() {
    return false;
  }
}
