package org.ek9lang.compiler.bytecode;

import java.util.List;
import org.ek9lang.compiler.support.SymbolCountCheck;

/**
 * Test bytecode generation for try-with-resources (single resource).
 * This test has showBytecode=true to output generated bytecode for validation.
 * Validates:
 * - Resource initialization before try block
 * - Automatic close() call in finally block
 * - Exception table includes finally handler
 * - Resource cleanup happens on normal and exception paths
 */
class TryWithSingleResourceTest extends AbstractExecutableBytecodeTest {

  public TryWithSingleResourceTest() {
    super("/examples/bytecodeGeneration/tryWithSingleResource",
        "bytecode.test",
        "TryWithSingleResource",
        List.of(new SymbolCountCheck("bytecode.test", 2)));
  }
}
